obj-$(CONFIG_BAIKAL_XGBE) += be-xgbe.o

be-xgbe-objs := xgbe-main.o xgbe-drv.o xgbe-dev.o \
		 xgbe-desc.o xgbe-ethtool.o xgbe-mdio.o \
		 xgbe-ptp.o

be-xgbe-$(CONFIG_BAIKAL_XGBE_DCB) += xgbe-dcb.o
be-xgbe-$(CONFIG_DEBUG_FS) += xgbe-debugfs.o
